### ISSUE TITLE
problem with a specific svg

### ISSUE THREAD

**Issue by sirogi** [appmancer/JXPlotterXVG#6]
Hi.

The law of issue conservation dictates that I open an issue, right after I close one.
This one is simple.. ish.

I am trying to process an SVG that has been generated same way as all the others, but for some reason, it's failing with java errors all over the place.

Just attached it. Yes it's supposed to be 11 Mb :)

Enjoy!

[errlog.txt](https://github.com/appmancer/JXPlotterXVG/files/1504788/errlog.txt)
[windmill_c.svg.zip](https://github.com/appmancer/JXPlotterXVG/files/1504786/windmill_c.svg.zip)

**Comment by appmancer** [comment]
Hi, 
There was a problem with SVG files that didn't provide the viewBox parameter in the SVG element.  I've fixed it now, and I've uploaded a feature build to http://fats.am/XPlotterSVG/1.1.1f/XPlotterSVG.jar
Can you download and test please?

**Comment by sirogi** [comment]
Hi,

The good news is, it's now processing the SVG that used to error out, and the output looks proper.
However, for whatever reason, the origin is off (midway up Y, los of negative Y coords). 

If I convert and test a file that used to work with no errors prior to the fix, origin for that one is appropriate (bottom left, no negative coordinates).

Both files had transforms applied in inkspace (for good measure, apples to apples comp.)
and consist of polylines.

**Comment by sirogi** [comment]
looking closer to the svg vs the gcode file, there seems to be a -1200 offset in Y. can't quite figure out where from, no matrices in the file. "Y +750" in the svg is mapping to "Y -550" in the gcode. X coord matches.

**Comment by appmancer** [comment]
I think it might be because it isn't in the template.  SVG works with an origin at the top left corner, and the XPlotter has an origin bottom left.  This means that I have to flip the image as I convert the coordinates, so things like writing don't come out as a mirror image.  To do that I need to know the size of the output area, which is one of the reasons I created the template.
Can you try copying the windmill into the template at http://fats.am/XPlotterSVG/XPlotterTemplate.svg and processing it from there.  That should resolve the origin issue.
I'll see if there is more I can do in code to prevent this issue as well.

**Comment by sirogi** [comment]
Sorry for the delay, haven't had a minute to look at this.
The latest download is missing the jar file. any idea where that might be?
Am using Zip file successive downloads, not fancy enough to install Git command line yet.

Will try the template file with the prior version, that should be an unrelated issue.

**Comment by sirogi** [comment]
Sure enough, using the template worked fine. 
I guess I was lucking out by using landscape A4s the whole time.

Easy fix! thanks.

**Comment by appmancer** [comment]
The latest stable build is always at http://fats.am/XPlotterSVG/XPlotterSVG.jar
I'm starting a tiny, poorly maintained and rarely updated blog at http://fats.am/blog
